---
- name: start newrelic
  service: name=newrelic-sysmond state=started enabled=yes
  tags: ['newrelic', 'newrelic_server']

- name: restart newrelic
  service: name=newrelic-sysmond state=restarted enabled=yes
  tags: ['newrelic', 'newrelic_server']

- name: start nginx-agent
  service: name=nginx-nr-agent state=started enabled=yes
  tags: ['newrelic', 'newrelic_nginx']

- name: restart nginx-agent
  service: name=nginx-nr-agent state=restarted enabled=yes
  tags: ['newrelic', 'newrelic_nginx']